### PR TITLE
Fixed lint error 126

### PR DESCRIPTION
**Pull request by luanvu1711**

### CODE REVIEW

**Review by aricrepp — APPROVED** [review]

**Review by aricrepp — APPROVED** [review]
Good changes so far, nice error fix

**Review by MrT3313 — CHANGES_REQUESTED** [review]
I have not checked functionality yet. 

please update the PR name based on coding conventions, add description, add images if possible

**Review by Ryan-webdev — APPROVED** [review]
I like how the landing page is designed, looks professional. Glad we were able to work through the fix.

**Review by MrT3313 — CHANGES_REQUESTED** [review]
Outside of the `test` files please remove all errors / warnings.

are you getting a clean console when you run the FE locally?

Screen Shot 2021-01-04 at 9 38 11 PM

**Comment by MrT3313** [comment]
Are we using styled components?

**Comment by MrT3313** [comment]
Is this PR name descriptive of the changes made?

**Pull request closed without merging**
