### PR TITLE
FEAT - LandingPage component

### PR DESCRIPTION
**Pull request by luanvu1711**
fixed errors with previous Landing Page, pushed new branch with new Landing Page

### CODE REVIEW

**Review by Ryan-webdev — APPROVED** [review]
Pulled remote works great for me. The page looks really professional looking. good job

**Review by aricrepp — APPROVED** [review]
Pulled remote, loads on my end, and design nice so far

**Comment by MrT3313** [comment]
1. Please remove all warnings that are not in a `test` file

Screen Shot 2021-01-05 at 6 44 27 PM

2. Are we using styled components in this project?

**Review by MrT3313 — CHANGES_REQUESTED** [review]
1. Please remove all warnings that are not in test files

Screen Shot 2021-01-05 at 6 44 27 PM

2. Are we using styled components?

3. Is there a better place for the Nav Bar? Is it really part of the landing page itself or a component imported and used within the landing page?

**Comment by luanvu1711** [comment]
we have decided to go with style-components. I built the navbar from scratch so i thought landing page was good place to put it. Should i move it to somewhere else?

**Comment by MrT3313** [comment]
There is an error with the `/` routes and pre build Okta flow on this current branch

Options: 
1. go back to the original routing & alter the LoginPage. Implement `landing page` changes  to `HomePage` component that is already implemented in the Okta flow

```
    <Switch>
      <Route path="/login" component={LoginPage} />
      <Route path="/implicit/callback" component={LoginCallback} />
      {/* any of the routes you need secured should be registered as SecureRoutes */}
      <SecureRoute
        path="/"
        exact
        component={() => <HomePage LoadingComponent={LoadingComponent} />}
      />
      <SecureRoute path="/example-list" component={ExampleListPage} />
      
      <SecureRoute path="/profile-list" component={ProfileListPage} />
      
      <Route component={NotFoundPage} />
    </Switch>
```

2. Try to just update the routes so that there is only one `/` route => either "/" = landing page & SecureRoute "/homepage" || "/landingPage" & SecureRoute "/"

**Pull request merged**
